AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

plugins:
  - standard-sorbet
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-sorbet

inherit_gem:
  standard-sorbet: config/base.yml

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Naming/FileName:
  Exclude:
    - 'lib/simplecov-ai.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'simplecov-ai.gemspec'
Metrics/ModuleLength:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
RSpec/ExampleLength:
  Enabled: true
  Max: 10

Gemspec/DevelopmentDependencies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 7

RSpec/NestedGroups:
  Enabled: true
  Max: 4
RSpec/MultipleExpectations:
  Enabled: true

Metrics/AbcSize:
  Enabled: true
Metrics/MethodLength:
  Enabled: true
Metrics/CyclomaticComplexity:
  Enabled: true
Metrics/PerceivedComplexity:
  Enabled: true

Gemspec/RequiredRubyVersion:
  Enabled: true
Style/Documentation:
  Enabled: true
Lint/MissingCopEnableDirective:
  Enabled: true
Style/ClassVars:
  Enabled: true
Style/ClassMethods:
  Enabled: true
RSpec/SpecFilePathFormat:
  Enabled: true
RSpec/SpecFilePathSuffix:
  Enabled: true
RSpec/DescribedClass:
  Enabled: true
ThreadSafety/ClassInstanceVariable:
  Enabled: true
  Exclude:
    - 'lib/simplecov-ai.rb'
Style/MultilineBlockChain:
  Enabled: true
Layout/LineLength:
  Enabled: true
  AllowedPatterns:
    - '> The total coverage deficit report exceeded'

Sorbet/ForbidTUntyped:
  Enabled: true

Sorbet/ForbidTUnsafe:
  Enabled: true

Sorbet/EnforceSignatures:
  Enabled: true

Sorbet/SignatureBuildOrder:
  Enabled: false

Sorbet/KeywordArgumentOrdering:
  Enabled: false

Sorbet/ForbidRBIOutsideOfAllowedPaths:
  Enabled: true
  Include:
    - '**/*.rbi'
  AllowedPaths:
    - 'sorbet/rbi/**/*.rbi'

Sorbet/ForbidExtendTSigHelpersInShims:
  Enabled: true
  Include:
    - '**/*.rbi'

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - 'bin/tapioca'
    - 'sorbet/tapioca/require.rb'
    - 'spec/**/*'

Sorbet/HasSigil:
  Enabled: true
  Exclude:
    - 'bin/tapioca'

Sorbet/FalseSigil:
  Enabled: true
  Exclude:
    - 'bin/tapioca'
