AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-sorbet

inherit_gem:
  standard-sorbet: config/base.yml

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Naming/FileName:
  Exclude:
    - 'lib/simplecov-ai.rb'

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'simplecov-ai.gemspec'
Metrics/ModuleLength:
  Enabled: true
Metrics/ClassLength:
  Enabled: true
  Max: 210
RSpec/ExampleLength:
  Enabled: true
  Max: 30
RSpec/MultipleExpectations:
  Enabled: true
  Max: 15
RSpec/MultipleMemoizedHelpers:
  Enabled: true
  Max: 10
Metrics/AbcSize:
  Enabled: true
  Max: 65
Metrics/MethodLength:
  Enabled: true
  Max: 50
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 20
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 20
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequiredRubyVersion:
  Enabled: true
Style/Documentation:
  Enabled: false
Lint/MissingCopEnableDirective:
  Enabled: true
Style/ClassVars:
  Enabled: true
Style/ClassMethods:
  Enabled: true
RSpec/FilePath:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
ThreadSafety/InstanceVariableInClassMethod:
  Enabled: true
  Exclude:
    - 'lib/simplecov-ai.rb'
Style/MultilineBlockChain:
  Enabled: false
Layout/LineLength:
  Enabled: true
  Max: 140
  AllowedPatterns:
    - '> The total coverage deficit report exceeded'

Sorbet/ForbidTUntyped:
  Enabled: true

Sorbet/ForbidTUnsafe:
  Enabled: true

Sorbet/EnforceSignatures:
  Enabled: true

Sorbet/SignatureBuildOrder:
  Enabled: false

Sorbet/KeywordArgumentOrdering:
  Enabled: false

Sorbet/ForbidRBIOutsideOfAllowedPaths:
  Enabled: false

Sorbet/ForbidExtendTSigHelpersInShims:
  Enabled: false

Sorbet/StrictSigil:
  Enabled: true
  Exclude:
    - 'bin/tapioca'
    - 'sorbet/tapioca/require.rb'
    - 'spec/**/*'

Sorbet/HasSigil:
  Enabled: true
  Exclude:
    - 'bin/tapioca'

Sorbet/FalseSigil:
  Enabled: true
  Exclude:
    - 'bin/tapioca'
