# typed: strict
# frozen_string_literal: true

require 'sorbet-runtime'
require 'simplecov'
require 'fileutils'
require 'pathname'

require_relative 'simplecov-ai/constants'
require_relative 'simplecov-ai/version'
require_relative 'simplecov-ai/configuration'
require_relative 'simplecov-ai/ast_resolver'
require_relative 'simplecov-ai/markdown_builder'

# The root namespace for the simplecov test coverage library.
module SimpleCov
  # Namespace containing all reporting formatters.
  module Formatter
    # Transforms raw simplecov coverage results into an AI-optimized markdown digest.
    # It addresses the context window limitations of LLMs by emitting token-efficient
    # reports and relying on AST-based semantic mapping to pinpoint exact methods
    # or classes with deficient coverage.
    class AIFormatter
      extend T::Sig

      # STDOUT notice printed after the report is written, unless the digest itself is echoed
      WRITTEN_MESSAGE = T.let('AI coverage digest written to %s', String)

      # Retrieves the global configuration for the AI formatter.
      # The instantiation pattern ensures that defaults are securely lazily loaded
      # before any coverage processing begins.
      #
      # @return [SimpleCov::Formatter::AIFormatter::Configuration] The active configuration state.
      sig { returns(SimpleCov::Formatter::AIFormatter::Configuration) }
      def self.configuration
        @configuration ||= T.let(Configuration.new, T.nilable(Configuration))
      end

      # Discards the memoized configuration so the next access starts from defaults. Primarily
      # useful for test isolation, where mutations to the process-global configuration would
      # otherwise leak between examples.
      #
      # @return [void]
      sig { void }
      def self.reset_configuration!
        @configuration = nil
      end

      # Yields the configuration object to a block, allowing consumers to override
      # default formatting behaviors, output paths, and token constraints before execution.
      #
      # @yieldparam config [Configuration] The global formatter configuration.
      # @return [void]
      sig { params(blk: T.nilable(T.proc.params(config: Configuration).void)).void }
      def self.configure(&blk)
        blk&.call(configuration)
      end

      # Orchestrates the formatting lifecycle to synthesize the markdown output. It converts
      # the raw result data using the internal MarkdownBuilder, enforces directory structures,
      # persists the digest to its destination and announces that destination on STDOUT (or,
      # when `output_to_console` is set, echoes the whole digest instead).
      #
      # @param coverage_metrics [SimpleCov::Result] The test coverage outcome generated by SimpleCov.
      # @return [void]
      sig { params(coverage_metrics: SimpleCov::Result).void }
      def format(coverage_metrics)
        config = self.class.configuration
        digest = MarkdownBuilder.new(coverage_metrics, config).build

        path = report_destination(config)
        FileUtils.mkdir_p(File.dirname(path))
        File.write(path, digest)

        puts(config.output_to_console ? digest : Kernel.format(WRITTEN_MESSAGE, path))
      end

      private

      # The report's destination: an explicit report_path (absolute as-is, relative against
      # SimpleCov.root, so the artifact is stable regardless of the working directory at exit)
      # or, by default, {Configuration::DEFAULT_REPORT_FILENAME} inside SimpleCov's coverage
      # directory so a custom `coverage_dir` is honoured.
      #
      # @param config [Configuration] The active configuration.
      # @return [String] An absolute filesystem path.
      sig { params(config: Configuration).returns(String) }
      def report_destination(config)
        if config.report_path_configured?
          absolute_report_path(config.report_path)
        else
          File.join(SimpleCov.coverage_path, Configuration::DEFAULT_REPORT_FILENAME)
        end
      end

      sig { params(report_path: String).returns(String) }
      def absolute_report_path(report_path)
        return report_path if Pathname.new(report_path).absolute?

        File.join(T.cast(SimpleCov.root, String), report_path)
      end
    end
  end
end
